### ISSUE TITLE
Key to show buffers and switch buffer freezes

### ISSUE THREAD

**Issue by Vouivre** [kyx0r/neatvi#1]
I opened two buffers in neatvi and I tested the command you implemented to switch buffers: ^s. 
As soon as I press "^s" vi freezes and I can do nothing. I have tested "^a" which works. 

Just tell me if you need more information.

**Comment by kyx0r** [comment]
Hello, I probably should have been more clear in the readme, but the idea there is when you press it it should show all the buffers you have, (max 8) and it waits for an argument between 1-8, so if you press for example combo like this ^s5(linefeed)(linefeed) it will switch to buffer 5. This is relatively new thing, I might change the way it works so that you don't have to press anything extra besides the number after ^s, since there are only single digit buffer count you can have, no need to verify the end of an input. Also I might change the buffers to range from 0-9 to maximize the single digit numbers for use. 
<a href="https://ibb.co/WsmNyWg"><img src="https://i.ibb.co/1bFYqf8/2020-12-03-150820-1366x768-scrot.png" alt="2020-12-03-150820-1366x768-scrot" border="0"></a>
where the list is printed depends on cursor position. Hope this helps, and thanks for checking out the fork! 

Answering your other question, I chose to build this editor instead of vim (though i've been using vim for a year+) simply because I think it does too much and I like to have full control of my programs. And C is just perfect for that.

**Comment by kyx0r** [comment]
Okay what I mentioned earlier is implemented now. I think it's more useful now.

**Comment by Vouivre** [comment]
Thank you for the explanation, but unfortunately it still doesn't work. Just keep in mind I'm a vim user and I don't know very well the differences between vi and vim. I just discovered I can get a list of all buffers by pressing ":b".

I have tested the keybinds "^a" and "^k" (recently implemented) and it works. What I expect when I press "^s": a list of buffers is displayed. I don't see a list of buffers. But I can do nothing more, I have to kill the process. Before testing it, I opened two buffers and I can switch betweend them with ":b 0" or ":b 1". 
For me "^s" means: Ctrl + s. I was not sure, but because "^a" and "^k" works as expected, I assume "Ctrl + s" is the right shortcuts. 

I have a minimal installation, perhaps I miss a library on my system. I use the KISS linux distribution, which is based on `musl`. My terminal is `st`. My shell at the moment is `zsh`, but it shouldn't be relevant. Is it possible it has something to do with the terminal ? If you tell me which one you are using, I could also test on my system. 

I can produce a debug log if necessary, but I don't know the step to get one. So I need some explanation to get one.

**Comment by kyx0r** [comment]
Oh, right. The fact that it locks up is actually correct behavior. It's not neatvi who is locking up, but rather your shell which intercepts the ^s key. Now I personally have the ^s in shell (bash) disabled, see in my bashrc [here](https://github.com/kyx0r/klec/blob/19922d8c0870bb0986bc8099ca5da099ce10e89e/dotfiles/.bashrc#L100-L101). I think it also works in zsh, just add that to your zshrc and test it out. Let me know if that helps, thanks.

**Comment by Vouivre** [comment]
I didn't knew about it. I had to add the same to my `.zshrc`. Now it works without problem. In between I discovered:

https://github.com/aligrudi/neatvi/issues/2

Thank you for your help!
