### ISSUE TITLE
Completion of filename

### ISSUE THREAD

**Issue by Vouivre** [kyx0r/neatvi#2]
As I can see, there is no completion for filenames when a new file is opened. I don't mean completion in the buffer, but when the command 

    :e myfile

is executed. I also don't see an history system for the ex commands. It frequently happens I have to open a file which is in another directory, and the path is not very short. With a completion system, I can avoid a typo. If each time I have to write

    :e path/mydocuments/2020/support/chemistry/exercise_24

I can expect to try to open it multiple times until there are no typo anymore. Not always, but it will happen.

Is it possible to implement something, or perhaps better, to have a workaround. I could imagine copying the path from a terminal or something like `dmenu`. 

You added a keybind for the filemanager `hund`. Is the idea to open the filemanager and to use it to open the file in `neatvi` ?

**Comment by kyx0r** [comment]
Well, what kind of file is exercise_24? For now I'll assume it has no file extension. So lets say you open vi in the bottom-most directory /path . If you want to open file called exersize_24 there are many ways to achieve that. You can: 
`
:inc exer
`
this will set a filter for files that have "exer" in them. 
then
`
:ea exer
`
this will open files that were filtered by the inc command but also they must have "exer" in them

Most of the time you will be aware of what kind of files there are so you can switch this up and run:
`
:inc 24`
`
:ea 24
`
and if there aren't any files that have "24" in them most likely it will take you to "path/mydocuments/2020/support/chemistry/exercise_24"

Ok, now lets say you have many files that go like exersize_24, exersize_23, exersize_22, exersize_21, ... etc
then it would make more sense to run 
`
:inc exer
`
then
`
:ea 24
`
You could also use hund to open files using "i", keep in mind that (enter, ^J, l) basically do the same as "i" but they will spawn a new process instead of opening in current vi. So it depends on the situation, for example it would be more efficient to use hund if your files are not of unique names and have very long filenames.

**Comment by kyx0r** [comment]
One problem may happen if you have multiple files named exersize_24 in different directories, in that case there is a bit of a fiddle to get to the file you want, but you would run it like this:
```
ea 24
ea 24 1
ea 24 2 
ea 24 3
...
```
until you find the instance that you want.
So I might implement a keybind to just cycle the instanced files so that it will be a lot faster.
As for actual file completion on the vi_prompt, it can be implemented, but I am not 100% convinced that it's necessary given the options that are available now.

**Comment by Vouivre** [comment]
I will be a little bit more precise. It often happens I open a file like this:

    cd ~/Documents/prof/school/module/math/exercises/class1/sheets/sheet1/
    vi sheet1_math.tex

Basically in my file `sheet1_math.tex` I have a references to some exercises like this:

    \input{numbers/exercise_number1.tex}

I use `LaTeX`. I have the exercise sheets in a directory and I have centralized all exercises in different directories. In vi, to edit an exercise I have to open

    :e ~/Documents/prof/course_exercises/bank/numbers/exercise_number_1.tex

for example. All exercises related to numbers in mathematics are grouped together but are not in the same directoy as the exercise sheets. I will take time to test your suggestions, perhaps I already have everything I need, I can't test for the moment.

Even if you don't implement a keybind for this case, why not letting the user chooses the filemanager ? As I understand you `hund` as to be used. I have to have a look at it. But probably `nnn` and `shfm` could be good choices. I don't know what you think about it and if it would be possible to customize it with the `config.h`. It woud be done of course in another issue.

**Comment by kyx0r** [comment]
The reason I don't let user choose filemanager is because hund is integrated in vi's source code. And anything else will have to be launched as separate program, which would not work very well because it would not be able to call back into vi for opening files. In that case you would need to add nnn's source code here and shfm is not written in C so it would not work. I usually try to avoid this kind of mess where the programs are not self contained binary, where they have to make calls to other scripts written in other languages, etc. This type of bloat is hard to debug and make any sense in no time. Unix philosophy suggests that it's okay for programs to call other programs, but there is a paradox that your program no longer "does one task and does it well" because it's no longer self contained to do that task rendering it useless if any component is missing. Some of the code between vi and hund is shared, so that allows to achieve way better inner operation and harmony long term while still being minimal enough. But as the whole idea of minimal C programs is so that anyone can have easy access to do customization in source code completely decentralized from maintainers. That is why for instance original neatvi version will never have any development, because it only implements the vi(1) spec and leaves anything extra for users to implement themselves. Exactly why I don't use vim because it's just too damn difficult to do customization in source code.  There is lots of baggage like python (+100MB++) ugly vimscript, dependency hell and I know that my brain is only extent of my skull.  So yeah, this fork is not really meant to make clone version of vim,  but more like a repo of specific patches so that if anybody wants to add features to their neatvi they might find it implemented here and save brain cycles thinking how to do something. One thing I did not do, was probably be better to have individual patches as .diff like on suckless.org. But it's so damn hard to maintain, cause like this repo have 35 patches, so it will be 35+ diffs. And each time something will mess up because one file change will require to change every patch offset, etc. So I just decided to run it as one big patch, this won't stop those who are interested anyway. 

Ehh, yeah I tend to go on tangents like that, do test out my previous suggestion. And if not good enough, feel free to leave suggestions on how else I can improve the neatvi, I will implement in no time if sensible.

**Comment by Vouivre** [comment]
Thank you for the exhaustive answer! I understand better why hund is used and it's not customizable. Sorry, I shouldn't have asked it in this issue. If someone else has the same question, not sure he will find it. Is it ok for you to open another issue, copy and paste your answer in it and then I will let you close the issue ? 

Back to the file opening. I have done some tests with `:inc` and `:ea`. Where are those commands documented ? I didn't know about them. I assume they are ex commands. But for example here:

http://manpages.ubuntu.com/manpages/precise/man1/ex.1posix.html#examples

I can't find anything about `:inc`. The same in the man page for vi. It's to know where it's documented, perhaps I can discover other features. I tried to search for `inc`, `filter`, have a more detailed look, but I was unable to find it in the documentation.

**Comment by kyx0r** [comment]
Yeah, those commands are exclusive to this fork. I made them, they are mentioned in the readme file. As I am still actively working on this fork it's likely that I will add more ex commands to do different things that are not standard. Like for example the next feature that I will soon implement will be a keybind that will automatically grab a word on the cursor and place it into ":%s//" regex on vi_prompt. Currently it's actually not trivial to do because the existing code is lacking such ability, but there is nothing I can't overcome. But as far as posix standard features for vi go I try to not change them, meaning that all the core keybinds will remain the same, so that any vi/vim user coming here will not have to relearn the keys, they would only need to learn the extra stuff which will only utilize unused key combinations without breaking the core posix functionality. 

It's okay, you can close the issue if you want, I will probably make like a FAQ section in the readme file with this answer.

**Comment by Vouivre** [comment]
I feel stupid, sorry. Of course it's written in the readme, I thought it was a `vi` or `ex` feature. 

I'm also not convinced a completion system must be implemented. First, we can use the given solution above. 

Second, you recently implemented a history buffer for `ex` commands, it can be also useful. 

Third, `hund` can be used.

If it's not enough, I tried `vis`. With this editor no buffers are available and the user has to use the wm instead of buffers. So it would be possible to use a wm in a stacking mode for example and to open the files in the terminal.

If you add a FAQ, it's not necessary to open an issue for the filemanager. 

Thank you for your help!

**Comment by kyx0r** [comment]
@Vouivre By the way, you can get filename completion in ex in a smart way. First open any nonexistant file, ie /tmp and run !ls /path/to/where/you/need . The ! will pipe output of ls into the tmp file opened in vi, then you enter insert mode and press ^g to index that output, after that you can use ^n and ^r to get completions for parts of the paths and names. This is kind of voodoo but it's nice to know that such thing actually is possible.

**Comment by Vouivre** [comment]
Interesting, thank you! It's pretty fun, your comment is on time! Last week-end I remembered `vis` in which there is no buffers. The idea is to use your wm to open multiple files and to manage them. I will test my idea and report it. I see pros and cons with that solution. I like the idea to combine existing tools to get what the user want. Is it ok for you to report it even if the issue is closed ? There is nothing to implement in your fork.
